spring.application.name=medical-fridge-backend
spring.datasource.url=jdbc:mysql://localhost:3306/medical_fridge_db
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.jpa.hibernate.ddl-auto=update